### ISSUE TITLE
Cannot find an overload for "PlatformParameters"

### ISSUE THREAD

**Issue by jagadish222** [AsrOneSdk/published-scripts#11]
Exception: Cannot find an overload for "PlatformParameters" and the argument count: "2".
At: $PlatformParameters = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParam
eters" `Line: 752; Char:27
StackTrace: 
at Get-Authentication, D:\extech\Telemed\Untitled1.ps1: line 752
at Start-CopyKeys, D:\extech\Telemed\Untitled1.ps1: line 1193
at <ScriptBlock>, D:\extech\Telemed\Untitled1.ps1: line 1410
CategoryInfo: InvalidOperation: New-Object, MethodException
An unknown exception occurred. Please contact support with the error details

**Comment by punit1396** [comment]
We had changed the Auth method to accommodate for the new AzureAD module. Could you try replacing the Get-Authentication method with the following?
```
### <summary>
### Gets the authentication result to key vaults.
### </summary>
function Get-Authentication
{
    # Vault resources endpoint
    $ArmResource = "https://vault.azure.net"

    # Well known client ID for AzurePowerShell used to authenticate scripts to Azure AD.
    $ClientId = "1950a258-227b-4e31-a9cf-717495945fc2"
    $RedirectUri = "urn:ietf:wg:oauth:2.0:oob"
    $AuthorityUri = "https://login.windows.net/$TenantId"
    $AuthContext = New-Object "Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext" `
        -ArgumentList $AuthorityUri
    $AuthResult = $AuthContext.AcquireToken($ArmResource, $ClientId, $RedirectUri, "Auto")

    return $AuthResult
}
```
