### ISSUE TITLE
WARNING: Unable to acquire token for tenant 'intentionally left blank'

### ISSUE THREAD

**Issue by jesuslopez11** [AsrOneSdk/published-scripts#13]
When running the Copy-keys.ps1, we are getting the following errors.

WARNING: Unable to acquire token for tenant 'intentionally left blank'
WARNING: Unable to acquire token for tenant 'intentionally left blank'

Exception: Cannot index into a null array.
At: $Longest = ($SubscriptionArray | Sort-Object Length -Descending)[0]Line: 730; Char:5
StackTrace: 
at Generate-UserInterface, C:\Users\user\Desktop\Copy-keys.ps1: line 730
at Start-CopyKeys, C:\Users\user\Desktop\Copy-keys.ps1: line 1170
at <ScriptBlock>, C:\Users\user\Desktop\Copy-keys.ps1: line 1410
CategoryInfo: InvalidOperation: , RuntimeException
An unknown exception occurred. Please contact support with the error details

**Comment by punit1396** [comment]
There seem to be no subscriptions under the tenant or the tenant couldn't be identified
