### ISSUE TITLE
CopyKeysSinglePass-Az.ps1 deprecated property used

### ISSUE THREAD

**Issue by msfreaks** [AsrOneSdk/published-scripts#14]
You are using a deprecated property on line 1266 of said script:

$BekSecretBase64 = $BekSecret.SecretValueText

In newer versions of the az module this will return empty, resulting in the script failing to complete secret-copies successfully.

Change line 1266 into:
$BekSecretBase64 = ($BekSecret.SecretValue | ConvertFrom-SecureString)

And it works like a charm

**Comment by punit1396** [comment]
Hi @msfreaks 

Thanks for this information. We were working on improving the entire script and have taken this change in as well.
