### ISSUE TITLE
Not loading the Target encryption details and execute option is disabled

### ISSUE THREAD

**Issue by VireshMathapati13** [AsrOneSdk/published-scripts#15]
I am trying this script as I have a VM which I replicated by providing all the details like source and target encryption key vaults. Still it's throwing error to manually update the target secret identifier so I am trying this script but see that below option are not loading and showing as Not applicable.

Disk encryption key vaults
Key encryption key vaults

![image](https://user-images.githubusercontent.com/19300396/102901403-94aa4480-4493-11eb-9790-da989141d3d8.png)

**Comment by punit1396** [comment]
Could you verify that the list of VMs is non-null. Based on the source RG input, we list the VMs in that source RG and source location that are ADE encrypted.
If there are no such VMs, we dont allow user to proceed

**Comment by punit1396** [comment]
Hi @VireshMathapati13 
This was a bug on our end. We hadn't handled the case wherein a 2-pass (with aad) encrypted VM would be decrypted and encrypted with 1-pass (without aad).
The fix has been checked in.

Thanks
