### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by ckotsidimos** [AsrOneSdk/published-scripts#9]
Which are the prerequisites to run the script?
Ia get the following error

`At C:\Users\user\keys1.ps1:245 char:6
+     [Microsoft.Azure.Management.Compute.Models.KeyVaultSecretReferenc ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [Microsoft.Azure.Management.Compute.Models.KeyVaultSecretReference].

At C:\Users\user\keys1.ps1:250 char:6
+     [Microsoft.Azure.Management.Compute.Models.KeyVaultKeyReference]$ ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unable to find type [Microsoft.Azure.Management.Compute.Models.KeyVaultKeyReference].
+ CategoryInfo          : ParserError: (:) [], ParseException
+ FullyQualifiedErrorId : TypeNotFound`

**Comment by punit1396** [comment]
There's already an issue opened for the same - [#6](https://github.com/AsrOneSdk/published-scripts/issues/6). Have pasted the fix below.

Manual workaround - Run `Import-Module Az.Compute` before running the script.
As for the script changes,
Uncomment and modify the required modules statement (line 26) to ensure Az.Compute is present in the current PS window context - `#Requires -Modules Az.Compute`
